# Generated by Django 4.2.8 on 2025-03-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='flat_number',
        ),
    ]
